CREATE OR ALTER TRIGGER TG_UPDATE_VALUE FOR VENDAITEM
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
    UPDATE VENDA
       SET VENDA.valortotal = (NEW.QUANTIDADE * NEW.VALOR)
     WHERE VENDA.codvenda   =  NEW.CODVENDA;
END;